// <auto-generated />
using System;
using DotNet9API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNet9API.Migrations
{
    [DbContext(typeof(VideoGameDbContext))]
    [Migration("20251026215902_VideoGameDetailsRelationship")]
    partial class VideoGameDetailsRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNet9API.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Insomniac Games",
                            Platform = "PS5",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "Spider-Man 2"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "Nintendo EPD",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "Santa Monica Studio",
                            Platform = "PS5",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "God of War Ragnarök"
                        },
                        new
                        {
                            Id = 4,
                            Developer = "FromSoftware",
                            Platform = "PS5",
                            Publisher = "Bandai Namco Entertainment",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 5,
                            Developer = "343 Industries",
                            Platform = "Xbox Series X",
                            Publisher = "Xbox Game Studios",
                            Title = "Halo Infinite"
                        },
                        new
                        {
                            Id = 6,
                            Developer = "Bethesda Game Studios",
                            Platform = "PC",
                            Publisher = "Bethesda Softworks",
                            Title = "Starfield"
                        },
                        new
                        {
                            Id = 7,
                            Developer = "Nintendo EPD",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "Super Mario Odyssey"
                        },
                        new
                        {
                            Id = 8,
                            Developer = "CD Projekt Red",
                            Platform = "PC",
                            Publisher = "CD Projekt",
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 9,
                            Developer = "Guerrilla Games",
                            Platform = "PS5",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "Horizon Forbidden West"
                        },
                        new
                        {
                            Id = 10,
                            Developer = "Rockstar Games",
                            Platform = "PS5",
                            Publisher = "Rockstar Games",
                            Title = "Red Dead Redemption 2"
                        });
                });

            modelBuilder.Entity("DotNet9API.Models.VideoGameDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoGameId")
                        .IsUnique();

                    b.ToTable("VideoGameDetails");
                });

            modelBuilder.Entity("DotNet9API.Models.VideoGameDetails", b =>
                {
                    b.HasOne("DotNet9API.Models.VideoGame", null)
                        .WithOne("VideoGameDetails")
                        .HasForeignKey("DotNet9API.Models.VideoGameDetails", "VideoGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNet9API.Models.VideoGame", b =>
                {
                    b.Navigation("VideoGameDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
